name: discourse

on:
  workflow_dispatch:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # At 00:00 on Sunday.
    # https://crontab.guru/#0_0_*_*_7
    - cron: "30 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - src_filename: web_only.yml
            tag_prefix: ""
          - src_filename: web_only_empty_discourse.yml
            tag_prefix: "empty-"
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Test
        run: |
          set -x
          docker version
          cat /etc/docker/daemon.json
          docker buildx version
          docker buildx ls

      - uses: zhulik/redis-action@1.1.0
        with:
          redis version: "7"
          number of databases: 100
      - name: Run PostgreSQL
        run: |
          docker run -d -p 5432:5432 --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 10 -e "POSTGRES_USER=postgres" -e "POSTGRES_PASSWORD=postgres" -e "POSTGRES_DB=discourse" -e GITHUB_ACTIONS=true postgres:15
      - name: Install dependencies
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7FCC7D46ACCC4CF8

          curl -sL https://github.com/discourse/discourse_docker/archive/main.tar.gz | tar xz
          cd discourse_docker-main
          cp samples/data.yml containers/
          cp ../${SRC_FILENAME} containers/web_only.yml
          # - sed -i "s/localhost/$(hostname)/g" "containers/web_only.yml"
        env:
            SRC_FILENAME: ${{ matrix.src_filename }}
      # - name: Prepare
      #   run: |
      #     sudo apt-get install -y postgresql-client
      #     psql -c 'create database discourse;' -U postgres
      - name: Build
        run: |
          cd discourse_docker-main
          ./launcher bootstrap web_only --docker-args "--network=host"
        env:
            TARGET_FILENAME: ${{ matrix.target_filename }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to Registry
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")

          docker tag local_discourse/web_only ghcr.io/unchartedsky/discourse:${TAG_PREFIX}latest
          docker tag local_discourse/web_only ghcr.io/unchartedsky/discourse:${TAG_PREFIX}sha-${git_hash}

          docker push ghcr.io/unchartedsky/discourse:${TAG_PREFIX}latest
          docker push ghcr.io/unchartedsky/discourse:${TAG_PREFIX}sha-${git_hash}
        env:
          TAG_PREFIX: ${{ matrix.tag_prefix }}
